### ISSUE TITLE
2020-03-18 topics to discuss

### ISSUE THREAD

**Issue by theo-armour** [ladybug-tools/spider-covid-19-viz-3d#16]
@paulmasson 

release management

- folder structure
- release management
- Theo's incessant wackiness
    - wants to run before merge
   - must allow for a sandbox 

code issues

- cannot keep adding more dev files because pushes stable
- index.html shows up when you view source - needs comments

visions

- new organization?
- separate timeline pages
- web pages for counties/provinces
- Translations
- better geoJson
- sound/music?
- positive tweets?
- rotation + zoom - 3D Lissajous path

**Comment by paulmasson** [comment]
@theo-armour it occurred to me after our conversation last night that the reason we are having merge problems is that you keep creating new files rather than leveraging Git. Every single one of your experiments should not be a separate file but a new branch based on the current stable version. You would still have every single bit of your history in Git, just not easily accessible like separate files.

But since I don't expect you to change, we'll have to make due with the discussed daily pause for input from others.

**Comment by paulmasson** [comment]
@theo-armour re: folder structure:

1) The top-level index file should be the stable version.

2) The support folders `maps` and `js` need to be in one place for use both by top-level stable index and all `dev` entries. The links to these files can be updated when moving to a new stable. 

3) You could use the current dev folder for all of your iterations and have the index file point to the last.

4) All the iterations in the archive should be moved to the dev folder and the remaining files deleted.

5) The remaining extraneous clutter should be move into the cookbook. Keep high-level folders to a minimum for ease of navigating the project.

**Comment by paulmasson** [comment]
@theo-armour as discussed on phone the top-level index file will point to a single stable version. The `js` folder will need to stay under the stable version, since the files therein will be updated along with dev iterations. Maps and images will reside in a top-level assets file.

**Comment by theo-armour** [comment]
@paulmasson 

I think most of the issues raised here have been dealt with.

The vision item have been added to the ToDo list in the readme
